# auto_sync = true
# sync_frequency = "10m"
# search_mode = "fuzzy"
filter_mode = "workspace"
workspaces = true
# filter_mode_shell_up_key_binding = "global"
# search_mode_shell_up_key_binding = "fuzzy"
style = "compact"
# inline_height = 0
# inline_height_shell_up_key_binding = 5
# invert = false
# show_preview = true
# exit_mode = "return-original"
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+",
# ]
# cwd_filter = [
#   "^/very/secret/area",
# ]
enter_accept = true
command_chaining = true
keymap_mode = "vim-insert"

[sync]
records = true
