[config.wallpaper]
command = "echo"
set = false

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/current-theme.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.openrgb]
input_path = './templates/primary.txt'
output_path = '~/.config/OpenRGB/primary.txt'
post_hook = "openrgb -c $(cat ~/.config/OpenRGB/primary.txt)"

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Documents/Notes/.obsidian/snippets/accent.css'
