[overview]
enter_command = ["hyprctl", "dispatch", "overview:toggle"]
locations = ["top_left"]
size = 10
timeout_ms = 100

[terminal]
enter_command = ["task-manager"]
locations = ["bottom_left"]
size = 5
timeout_ms = 100

[music]
enter_command = ["hyprctl", "dispatch", "togglespecialworkspace", "music"]
locations = ["bottom_right"]
size = 5
timeout_ms = 100
