[pyprland]
plugins = ["scratchpads", "magnify", "fetch_client_menu", "toggle_special"]

[scratchpads.template]
unfocus = "hide"
lazy = true
hysteresis = 0
max_size = "100% 100%"
margin = 10
close_on_hide = true
hide_delay = 1

[scratchpads.calc]
use = "template"
animation = "fromBottom"
command = "kitty --app-id=calc -- qalc -i"
class = "calc"
size = "40% 20%"

[scratchpads.notes]
use = "template"
animation = "fromRight"
command = "kitty --app-id=todo -- nvim ~/Documents/Notes/todo.md"
class = "todo"
size = "500px 800px"

[scratchpads.btop]
use = "template"
animation = "fromBottom"
command = "kitty --app-id=task-manager btop"
class = "task-manager"
size = "90% 90%"

[scratchpads.music]
use = "template"
process_tracking = false
animation = "fromBottom"
command = "firefox --new-window music.youtube.com"
match_by = "title"
title = "YouTube Music â€” Mozilla Firefox"
size = "90% 90%"
