[pyprland]
plugins = ["scratchpads", "magnify", "fetch_client_menu", "toggle_special"]

[scratchpads.template]
unfocus = "hide"
lazy = true
hysteresis = 0
max_size = "100% 100%"
margin = 10
close_on_hide = true
hide_delay = 1

[scratchpads.calc]
use = "template"
animation = "fromBottom"
command = "kitty --app-id=calc -- qalc -i"
class = "calc"
size = "40% 20%"
