"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = '▶▶ '

add_newline = true

palette = "noctalia"

format = """
[╭─](fg:outline)\
[](fg:primary)\
$directory\
[](fg:primary bg:surface)\
$git_branch\
$git_status\
[](fg:surface bg:secondary)\
$nodejs\
[](fg:secondary)
[╰─](fg:outline)$character\
"""

[directory]
style = "fg:surface bg:primary"
format = "[ $path ]($style)"

[directory.substitutions]
"chezmoi" = " "
"digital-publishing-services" = "DPS"
"/Coding" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:surface"
format = '[[ $branch ](fg:primary bg:surface)]($style)'

[git_status]
style = "bg:surface"
format = '[[($all_status$ahead_behind) ](fg:primary bg:surface)]($style)'

[nodejs]
symbol = ""
style = "bg:surface"
format = '[[$symbol ($version) ](fg:on_secondary bg:secondary)]($style)'

[palettes.noctalia]
primary = "{{colors.primary.default.hex}}"
on_primary = "{{colors.on_primary.default.hex}}"
primary_container = "{{colors.primary_container.default.hex}}"
on_primary_container = "{{colors.on_primary_container.default.hex}}"
secondary = "{{colors.secondary.default.hex}}"
on_secondary = "{{colors.on_secondary.default.hex}}"
secondary_container = "{{colors.secondary_container.default.hex}}"
on_secondary_container = "{{colors.on_secondary_container.default.hex}}"
tertiary = "{{colors.tertiary.default.hex}}"
on_tertiary = "{{colors.on_tertiary.default.hex}}"
tertiary_container = "{{colors.tertiary_container.default.hex}}"
on_tertiary_container = "{{colors.on_tertiary_container.default.hex}}"
surface = "{{colors.surface.default.hex}}"
on_surface = "{{colors.on_surface.default.hex}}"
surface_variant = "{{colors.surface_variant.default.hex}}"
on_surface_variant = "{{colors.on_surface_variant.default.hex}}"
surface_dim = "{{colors.surface_dim.default.hex}}"
surface_bright = "{{colors.surface_bright.default.hex}}"
surface_container = "{{colors.surface_container.default.hex}}"
error = "{{colors.error.default.hex}}"
on_error = "{{colors.on_error.default.hex}}"
shadow = "{{colors.shadow.default.hex}}"
outline = "{{colors.outline.default.hex}}"
